### ISSUE TITLE
статьи для журнала

### ISSUE THREAD

**Issue by Palladiy46** [veterinary-salons/frontend#149]
статьи здесь: 
https://docs.google.com/document/d/1-xB8HigZq0yRsbYpBReuNAfHwZ6ZLWHmtJeoaM6J9RI/edit?usp=sharing

**Comment by Palladiy46** [comment]
Полина, вот задача на картинки для дизайнеров
https://github.com/orgs/veterinary-salons/projects/1/views/2?pane=issue&itemId=39553808

**Comment by Polina-KHV** [comment]
![Image](https://github.com/veterinary-salons/frontend/assets/113764110/e8d6deb4-feab-4efc-987c-7b6ddf9e452b)
