### ISSUE TITLE
Верстка компонентов: формы

### ISSUE THREAD

**Issue by AlinaLvova** [veterinary-salons/frontend#3]
Forms:

- [x] элемент с двумя опциями выбора

![Image](https://user-images.githubusercontent.com/37267494/260712307-b8212e03-b542-4347-8d67-468e01a0a7ad.png)

- [x] элемент с тремя опциями выбора

![Image](https://user-images.githubusercontent.com/37267494/260712365-edaccbe5-a86b-4a73-8c4c-dc5282274f04.png)

Inputs:

- [ ] поле ввода текста 

- [ ] поле ввода текста в поисковой строке

- [x] check-box с иконкой дом (стиль 1)

![Image](https://user-images.githubusercontent.com/37267494/260723727-ab065318-4ec8-40af-8c1c-0b67ca5b3489.png)

- [x] check-box с иконкой квадрат с фоном(стиль 2)

![Image](https://user-images.githubusercontent.com/37267494/260723848-3879ad73-d53e-441f-a3ff-e84c2eb02837.png)

- [x] radio-button с иконкой квадрат без фона (стиль 3) 
![Image](https://user-images.githubusercontent.com/37267494/260724401-8f361686-0696-4224-a705-590b34b81caf.png)

- [x] radio-button с иконкой круг (стиль 4)
![Image](https://user-images.githubusercontent.com/37267494/260724459-bb7f2a5a-0076-47e9-a841-000a90d50ac4.png)

- [x] check-box (стиль 5)
![Image](https://user-images.githubusercontent.com/37267494/260724892-cd950227-b1ba-4674-a01a-e50c76c77aa4.png)

- [x] check-box (стиль 6)
![Image](https://user-images.githubusercontent.com/37267494/260725038-7ea1bd06-16ad-4a41-82cd-829af3a5557c.png)

❗Важно: нужно придумать название элементам.

**Comment by vivan1992** [comment]
готово, без инпутов, инпуты сделал антон
