### ISSUE TITLE
Верстка компонента: Окно уведомления

### ISSUE THREAD

**Issue by Polina-KHV** [veterinary-salons/frontend#80]

**Comment by Polina-KHV** [comment]
![Image](https://github.com/veterinary-salons/frontend/assets/113764110/6e5a428b-bbea-49ec-91a2-cc8f2c71b554)

**Comment by Polina-KHV** [comment]
![Image](https://github.com/veterinary-salons/frontend/assets/113764110/33999dfa-3c47-4fd8-a116-060577bf0911)

**Comment by AlinaLvova** [comment]
@Polina-KHV доделано?
